### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by phampyk** [benjaminjonard/mendako#167]
I can help with spanish translation if you want

**Comment by benjaminjonard** [comment]
That would be great ! 
I added spanish to Crowdin, you should have access to it [here](https://crowdin.com/translate/mendako/169/en-es)

**Comment by phampyk** [comment]
Done, just 2 translations I would need some input as I need some context for them

**Comment by benjaminjonard** [comment]
Thank you very much for your time, it will be part of the next release :+1:
