### ISSUE TITLE
Add Portuguese Brazil

### ISSUE THREAD

**Issue by lucsdev25** [benjaminjonard/mendako#307]
Looks like there's no Portuguese in the project, so I gladly ask you to add it and I promise I'll translate it and proofread it.

**Comment by benjaminjonard** [comment]
Hello, I added Portuguese (Brazilian) to the project, you should now be able to access it here: https://crowdin.com/project/mendako/pt-BR

Feel free to ask if you have any questions. Thank you very much for your help and time !

**Comment by lucsdev25** [comment]
You're welcome
